// firebase core
import firebase from 'firebase/app'

// firebase features that we want to use - we want the firestore database
import 'firebase/firestore'

// firebase config object generated by firebase backend project
const firebaseConfig = {
    apiKey: "AIzaSyDAtiJiCzzCRvl7-DbJqDoeNLv2o3aK8t0",
    authDomain: "medi-store-eef3b.firebaseapp.com",
    projectId: "medi-store-eef3b",
    storageBucket: "medi-store-eef3b.appspot.com",
    messagingSenderId: "102430235092",
    appId: "1:102430235092:web:1b6991d34b84a154011e41"
  };

  // initialize firebase - this method connects to our firebase backend which allows us to use any services like the firestore that we want
  firebase.initializeApp(firebaseConfig)

  // initialize services - we also have to initialize the services and this returns an object that we can use to interact with firestore
  const projectFirestore = firebase.firestore()

  export { projectFirestore }



  // firebase setup - this project is using firebase version 8.5
